<?php

namespace Despawn\Providers;

use Despawn\Resources\CategoryResource;
use Filament\PluginServiceProvider;

class DespawnAdminServiceProvider extends PluginServiceProvider
{
    protected array $resources = [
        CategoryResource::class
    ];

    protected array $pages;

    protected array $widgets;

//    public function boot()
//    {
//        // Needs to automatically collect and register all resources within filament directory
//        // Needs to automatically collect and register all widgets within filament directory
//        // Needs to override filament configs and potentially somehow override footer / logos
//    }

    public function configurePackage(\Spatie\LaravelPackageTools\Package $package): void
    {
        $package
            ->name('despawn-admin');
    }

    public function packageRegistered(): void
    {
        parent::packageRegistered(); // TODO: Change the autogenerated stub

//        $this->mergeConfigFrom(__DIR__ . '/../config/despawn-admin.php', 'filament');
    }
}